### ISSUE TITLE
Items are being dissapeared from cart when user logs out 

### ISSUE THREAD

**Issue by Salidor** [IuliiaKonovalova/e-commerce#349]
Items are being dissapeared from cart when user logs out. With wishlist it stays there even if user logs out but with bag it doesn't save it there.

**To Reproduce**
1. Add to bag an item
2. Log out
3. Log in
4. Go to bag and see the item is missing.

**Comment by IuliiaKonovalova** [comment]
Thank you very much for pointing it out! I will investigate it later as this project is under assessment at this time, and I am not allowed to make any changes to my school projects till I receive my Diploma. I would gladly appreciate it if you share your name as you have developed a vast interest in my project. Also, if you have any issues from your end, you can leave a comment here, and I will try to help you out.

**Comment by Salidor** [comment]
Np Iuliia. My name is Saul. 

I liked your project and I'd like to contribute if you don't mind. For now I am just checking for bugs etc. I found some stuff that could be improved. For instance, by choosing the color of an item it should automatically switch it to the image with that color. By adding an item to the wishlist it should update it in the navbar as it does with the bag. And so on.

P.S. I didn't find the way to leave a review on item.

**Comment by IuliiaKonovalova** [comment]
Thank you very much for your kind words! When it comes to reviews, the user is able to add a review only when the order has been made an order and the order has the status "completed". The order's status can be changed only by an admin or logistics manager. In this case, the reviews are genuine.
![image](https://user-images.githubusercontent.com/78818359/189483990-cbdf6f7c-3a88-4bb2-8c6c-b92055d92dfd.png)

**Comment by Salidor** [comment]
Thank you again for detailed explanation. One last thing. Could you please give me an example of use of these sections?

- Product attribute values
- Product attribute valuess
- Product attributes
- Product type attributes
- Product types

Thank you in Advance and good luck with your diploma.
Wish you the best.

**Comment by IuliiaKonovalova** [comment]
Thank you very much!)

- Product types are needed to set the type of the product (shoes or oreo-cookies)
- Product attributes are needed to set possible attributes for each product type:

1. shoes can have **size** (35, 36, etc.) and **color** (red, blue, etc)
2. cookies can have different **taste** (chocolate, vanilla, etc)
3. notebooks can have different **size** (A5, B5, etc) and **color** (red, blue, etc)

- Product attribute values are needed to set reusable values for particular attribute

1. shoes sizes: 35 - 45...
2. color: red, green,...
3. taste: stawberry, blueberry...

This structure allows to reuse attributes (and values pointed at these attributes) for different product types

- Product attribute valuess controls uniqueness, it will not allow to add the same value to an attribute
If a manager has already created attribute "color" and value for this attribute "yellow", they will not be able to add the same pair to DB
- The same goes with Product type attributes: if a manager has already created shoes and assigned attribute for "shoes" - "size", it will be impossible to add the same attribute "size" to a "shoes" product type
